/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Vector;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

import java.io.*;
/**
 *
 * @author alegAsus
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        borrowertab = new javax.swing.JPanel();
        SSNTextField = new javax.swing.JTextField();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        AddressTextField = new javax.swing.JTextField();
        AddBorrowerButton = new javax.swing.JButton();
        lookuptab = new javax.swing.JPanel();
        SearchField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        finestab = new javax.swing.JPanel();
        viewfinesbutton = new javax.swing.JButton();
        checkouttab = new javax.swing.JPanel();
        borrowerID = new javax.swing.JTextField();
        isbncheckout = new javax.swing.JTextField();
        CheckoutButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        checkinisbn = new javax.swing.JTextField();
        checkingborrowernumber = new javax.swing.JTextField();
        checkinbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("McDermott Library Book Database");

        SSNTextField.setText("SSN");

        FirstNameTextField.setText("First Name");

        LastNameTextField.setText("Last Name");

        AddressTextField.setText("Address");

        AddBorrowerButton.setText("Add");
        AddBorrowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBorrowerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout borrowertabLayout = new javax.swing.GroupLayout(borrowertab);
        borrowertab.setLayout(borrowertabLayout);
        borrowertabLayout.setHorizontalGroup(
            borrowertabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowertabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(borrowertabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borrowertabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(AddressTextField)
                        .addComponent(LastNameTextField)
                        .addComponent(FirstNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .addComponent(SSNTextField))
                    .addComponent(AddBorrowerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(534, Short.MAX_VALUE))
        );
        borrowertabLayout.setVerticalGroup(
            borrowertabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrowertabLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(SSNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddBorrowerButton)
                .addContainerGap(367, Short.MAX_VALUE))
        );

        tabs.addTab("Add Borrowers", borrowertab);

        SearchField.setText("101010");
        SearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchFieldActionPerformed(evt);
            }
        });

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Search with any combination of ISBN, Book Title, Author(s) seperating each field with a ~");

        javax.swing.GroupLayout lookuptabLayout = new javax.swing.GroupLayout(lookuptab);
        lookuptab.setLayout(lookuptabLayout);
        lookuptabLayout.setHorizontalGroup(
            lookuptabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lookuptabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lookuptabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lookuptabLayout.setVerticalGroup(
            lookuptabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lookuptabLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchButton)
                .addContainerGap(438, Short.MAX_VALUE))
        );

        tabs.addTab("Book Lookup", lookuptab);

        viewfinesbutton.setText("View Fines Table");
        viewfinesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewfinesbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout finestabLayout = new javax.swing.GroupLayout(finestab);
        finestab.setLayout(finestabLayout);
        finestabLayout.setHorizontalGroup(
            finestabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finestabLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(viewfinesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        finestabLayout.setVerticalGroup(
            finestabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finestabLayout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(viewfinesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        tabs.addTab("Fines", finestab);

        borrowerID.setText("Borrower Number");
        borrowerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowerIDActionPerformed(evt);
            }
        });

        isbncheckout.setText("ISBN");

        CheckoutButton.setText("Checkout");
        CheckoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout checkouttabLayout = new javax.swing.GroupLayout(checkouttab);
        checkouttab.setLayout(checkouttabLayout);
        checkouttabLayout.setHorizontalGroup(
            checkouttabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkouttabLayout.createSequentialGroup()
                .addGroup(checkouttabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkouttabLayout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(CheckoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(checkouttabLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addGroup(checkouttabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(borrowerID, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isbncheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        checkouttabLayout.setVerticalGroup(
            checkouttabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkouttabLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(borrowerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(isbncheckout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(CheckoutButton)
                .addContainerGap(265, Short.MAX_VALUE))
        );

        tabs.addTab("Checkout", checkouttab);

        checkinisbn.setText("ISBN");

        checkingborrowernumber.setText("Borrower Number");

        checkinbutton.setText("Checkin");
        checkinbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkinisbn)
                            .addComponent(checkingborrowernumber, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(checkinbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(checkinisbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(checkingborrowernumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(checkinbutton)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        tabs.addTab("Checkin", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabs)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        
    
    //!!!IMPORTANT!!!
    private void SearchFieldActionPerformed(java.awt.event.ActionEvent evt) {                                            
        
    }                                           
    
    //!!!IMPORTANT!!!
    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String text = SearchField.getText(); //will throw exception if null
        System.out.println("text captured:" + text);
        String connectorQuery = queryGeneration(text);
        System.out.println("Query: " + connectorQuery);
        System.out.println(connectorQuery);
        try {
			Class.forName("com.mysql.jdbc.Driver");
			Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbfinal?characterEncoding=latin1", "root", "#tabebuiA5");
			Statement stmt = con.createStatement();
			
			PreparedStatement st = (PreparedStatement) con.prepareStatement(connectorQuery);
            System.out.println("Going to execute query");
            
			ResultSet rs = st.executeQuery(connectorQuery);
			if(rs.isBeforeFirst() == false) {
				System.out.println("Result set is null");
			}
			System.out.println("Query has been executed");
			
			//lookuptable.setModel(DbUtils.resultSetToTableModel(rs));
			
			// It creates and displays the table
			javax.swing.JTable table = new javax.swing.JTable(buildTableModel(rs));
			
		    // Closes the Connection

		    JOptionPane.showMessageDialog(null, new JScrollPane(table));
			
			//while (rs.next())
				//System.out.println(rs.getString(1) + "  " + rs.getString(2) + "  " + rs.getString(3) + "  " + rs.getInt(4));
			
			con.close();
		} catch (Exception e) {
			System.out.println(e);
                }
		
    }                                            

    public static DefaultTableModel buildTableModel(ResultSet rs)
    	    throws SQLException {

    	ResultSetMetaData metaData = rs.getMetaData();

    	// names of columns
    	Vector<String> columnNames = new Vector<String>();
    	int columnCount = metaData.getColumnCount();
    	for (int column = 1; column <= columnCount; column++) {
    	    columnNames.add(metaData.getColumnName(column));
    	}

    	// data of the table
    	Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    	while (rs.next()) {
    	    Vector<Object> vector = new Vector<Object>();
    	    for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
    	        vector.add(rs.getObject(columnIndex));
    	    }
    	    data.add(vector);
    	}

    	return new DefaultTableModel(data, columnNames);

    	}
    //!!!IMPORTANT!!!
    private void AddBorrowerButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    	// TODO add your handling code here:
        String ssn= SSNTextField.getText();
        String fName= FirstNameTextField.getText();
        String lName= LastNameTextField.getText();
        String address= AddressTextField.getText();
try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbfinal?characterEncoding=latin1", "root", "#tabebuiA5");
        Statement stmt = con.createStatement();

        if(SSNTextField.getText().equals("") && FirstNameTextField.getText().equals("") && LastNameTextField.getText().equals("") && AddressTextField.getText().equals(""))
        {
                JOptionPane.showMessageDialog(null, "Error. Value must not be null. Try again.");
        }


        else{
                ResultSet rs1 = stmt.executeQuery("select * from dbfinal.borrowers where SSN='"+ssn+"';");

                if(rs1.next())
                {
                        JOptionPane.showMessageDialog(null, "The borrower already exists in the system");
                        SSNTextField.setText("");
                }

                Statement stmt2=con.createStatement();
                ResultSet rs2 = stmt2.executeQuery("select max(card_ID) from dbfinal.borrowers;");

                Statement stmt3=con.createStatement();
                
                
                
                String queryString = "";
                 queryString = String.format("INSERT INTO dbfinal.borrowers(SSN, First_Name, Last_Name, Address) values('%s', '%s', '%s', '%s');",ssn,fName,lName,address);
                System.out.println("Borrower Query created");
                stmt3.executeUpdate(queryString);
                System.out.println("Borrower Query executed");
                SSNTextField.setText("");
                FirstNameTextField.setText("");
                LastNameTextField.setText("");
                AddressTextField.setText("");

        }
        con.close();
    }
    catch (Exception e) {
  System.out.println(e);
        }
    }                                                 
    
    //!!!IMPORTANT!!!
    private void viewfinesbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                                
    	String date = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());

    	try {
    	Class.forName("com.mysql.jdbc.Driver");
    	Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Library?characterEncoding=latin1", "root", "Syonarain1");
    	Statement stmt = con.createStatement();
    	ResultSet rs1=stmt.executeQuery("Select * from book_loans where  Due_date<'"+date+"';");

    	while(rs1.next())
    	{
    	  DateFormat format = new SimpleDateFormat("yyyy-MM-dd");
    	  int loan_id = Integer.parseInt(rs1.getString(1));
    	  String dueDate = rs1.getString(5);
    	  String dateIn = rs1.getString(6);
    	  java.util.Date due=format.parse(dueDate);
    	  java.util.Date today=format.parse(date);
    	  double fineAmt,daysLate;
    	  if (dateIn == null)
    	  {


    	    daysLate = today.getTime() - due.getTime();
    	    daysLate = daysLate/(1000*24*24*60);
    	    fineAmt = .25*daysLate;
    	  }
    	  else if (format.parse(dateIn).getTime() > due.getTime())
    	  {
    	    java.util.Date in = format.parse(dateIn);
    	    daysLate = in.getTime() - due.getTime();
    	    daysLate = daysLate/(1000*24*24*60);
    	    fineAmt = .25*daysLate;
    	  }
    	  else
    	  {
    	    continue;
    	  }


    	  Statement stmt2 = con.createStatement();
    	  ResultSet rs2 = stmt2.executeQuery("select * from fines where loan_ID ="+loan_id+";");
    	  if(rs2.next())
    	  {
    	    Statement stmt3 = con.createStatement();
    	    stmt3.executeUpdate("update fines set fine_amt = "+fineAmt+" where loan_ID ="+loan_id+";");

    	  }
    	  else
    	  {
    	    Statement stmt4 = con.createStatement();
    	    stmt4.executeUpdate("INSERT INTO fines (loan_ID,fine_amt, Paid) VALUES ("+loan_id+","+fineAmt+",0);");
    	  }
    	  con.close();

    	}

    	} catch(Exception e)
    	{
    	  System.out.println(e);
    	}

    }                                               

    private void CheckoutButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void borrowerIDActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void checkinbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        String isbn = checkinisbn.getText();
        String card = checkingborrowernumber.getText();


        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/SQL_Library?characterEncoding=latin1", "root", "rodri354#");
            Statement stmt = con.createStatement();

            if(checkinisbn.getText().equals("") && checkingborrowernumber.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "Error. Value must not be null. Try again.");
            }
            else{

                Statement stmt1 = con.createStatement();
                stmt1.executeQuery("Select loan_ID, ISBN, card_ID from SQL_Library.book_loans WHERE ISBN = "+isbn+" AND card_ID = "+card+" AND date_in IS null;");


                Statement stmt2 = con.createStatement();
                stmt2.executeUpdate("INSERT INTO dbfinal.book_loans(date_in) values(DATETIME);");

            }
            con.close();
        }
        catch (Exception e) {
      System.out.println(e);
            }

    }                                             
    
    //!!!IMPORTANT!!!
    private static String queryGeneration(String textfield){
        int counter = 0;
        String query = " ";
        
        int count = 0;

        for(int i=0; i < textfield.length(); i++)
        {    if(textfield.charAt(i) == '\t')
                count++;
        }
        String field1 = "";
        String field2 = "";
        String field3 = "";
        
        if(count == 1) {
        	int subIndex = textfield.indexOf("\t");
        	field1 = textfield.substring(0,subIndex);
        }
        else if(count == 2) {
        	int subIndex = textfield.indexOf("\t");
        	field1 = textfield.substring(0,subIndex);
        	field2 = textfield.substring(subIndex);
        }
        
    	List<Pattern> patterns = new ArrayList<>();
        
        //only isbn
        patterns.add(Pattern.compile("^(\\d{10}|\\d{13})$"));

        //only title or only author
        patterns.add(Pattern.compile("^[^~]+$"));

        //isbn and title and author
        patterns.add(Pattern.compile("^(\\d{10}|\\d{13})[~].+[~].+$"));
        patterns.add(Pattern.compile("^.+[~](\\d{10}|\\d{13})[~].+$"));
        patterns.add(Pattern.compile("^.+[~].+[~](\\d{10}|\\d{13})$"));

        //isbn and title/author
        patterns.add(Pattern.compile("^(\\d{10}|\\d{13})[~].+$"));
        patterns.add(Pattern.compile("^.+[~](\\d{10}|\\d{13})$"));

        //title and author
        patterns.add(Pattern.compile("^.+[~].+$"));

        for(Pattern pattern : patterns) {
			if(pattern.matcher(textfield).matches()) {
				//only isbn
				if(counter == 0) {
					return query = String.format("SELECT book.ISBN, Title, Name AS Author, Availability From dbfinal.book, dbfinal.book_authors AS A, "
							+ "dbfinal.authors AS B WHERE book.ISBN = '%s' AND A.ISBN = '%s' AND A.author_ID = B.author_ID;",textfield,textfield);
					
				}
				//only title or author
				if(counter == 1) {
					System.out.println("In author only");
					query = String.format("SELECT book.ISBN, Title, Name AS Author, Availability From dbfinal.book, dbfinal.book_authors AS A, dbfinal.authors AS B " + 
							"WHERE book.Title LIKE '%%%s%%' AND A.author_ID = B.author_ID " + 
							" AND book.ISBN = A.ISBN;",textfield);
					System.out.println("Query created");
					return query;
					
				}
				//isbn and title and author
				if((counter == 2) || (counter == 3) || (counter == 4)) {
					System.out.println("//isbn and title and author");
					int subIndex = textfield.indexOf("~");
					int subIndex2 = textfield.lastIndexOf("~");
		        	field1 = textfield.substring(0,subIndex);
		        	field2 = textfield.substring(subIndex+1,subIndex2);
		        	field3 = textfield.substring(subIndex2+1);
		        	System.out.println(field1);
		        	System.out.println(field2);
		        	System.out.println(field3);
		  
					query = String.format("SELECT book.ISBN, Title, name AS Author, Availability " + 
							"From dbfinal.book, dbfinal.book_authors AS A, dbfinal.authors AS B " + 
							"WHERE book.ISBN = '%s' AND A.ISBN = '%s' " + 
							"  AND Title LIKE '%%%s%%' " + 
							"  AND name LIKE '%%%s%%';",field1,field1,field2,field3);
					System.out.println("Query created");
					return query;
				}
				//isbn and title/author
				if((counter == 5) || (counter == 6)) {
					int subIndex = textfield.indexOf("~");
		        	field1 = textfield.substring(0,subIndex);
		        	field2 = textfield.substring(subIndex+1);
		        	System.out.println(field1);
		        	System.out.println(field2);
		        	
					System.out.println("In isbn and title/author");
					query = String.format("SELECT book.ISBN, Title, name AS Author, Availability From dbfinal.book, dbfinal.book_authors AS A, dbfinal.authors "
							+ "AS B WHERE book.ISBN = '%s' AND A.ISBN = '%s' "
							+ "AND A.author_ID = B.author_ID AND Title = '%s';",field1,field1,field2);
					System.out.println("Query created");
					return query;
				}
		        //title and author
				if(counter == 7) {
					System.out.println("In title and author");
					int subIndex = textfield.indexOf("~");
		        	field1 = textfield.substring(0,subIndex);
		        	field2 = textfield.substring(subIndex+1);
		        	System.out.println(field1);
		        	System.out.println(field2);
					query = String.format("SELECT book.ISBN, Title, name AS Author, Availability From dbfinal.book, dbfinal.book_authors AS A, "
							+ "dbfinal.authors AS B WHERE  name LIKE '%%%s%%' AND Title LIKE '%%%s%%'" + 
							"    AND book.ISBN = A.ISBN;",field1,field2);
					return query;
				}
			}
			counter++;
        }
        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AddBorrowerButton;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JButton CheckoutButton;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JTextField SSNTextField;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchField;
    private javax.swing.JTextField borrowerID;
    private javax.swing.JPanel borrowertab;
    private javax.swing.JButton checkinbutton;
    private javax.swing.JTextField checkingborrowernumber;
    private javax.swing.JTextField checkinisbn;
    private javax.swing.JPanel checkouttab;
    private javax.swing.JPanel finestab;
    private javax.swing.JTextField isbncheckout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel lookuptab;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JButton viewfinesbutton;
    // End of variables declaration                   
}
